name: weekly release

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * 0'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CI_COMMIT_AUTHOR: Continuous Integration

    steps:
      - uses: actions/checkout@v4

      - name: install guix
        run: sudo apt update && sudo apt install guix

      - name: compile
        run: make update

      - name: commit & push
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "thaenz@pm.me"
          git commit -am 'update hosts.scm'
          git push

      - name: create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$(date +'%d-%m-%Y')" \
             --title "$(date +'%d-%m-%Y')" \
             --notes "guix hash: $(guix hash hosts.gz)" \
             hosts.gz
